[package]
name = "http-server"
version = "0.1.0"
authors = ["Antoine Latrille <antoine.latrille@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.0"
hashbrown = "0.3"
listenfd = "0.3"
futures = "0.1.27"
bytes = "0.4.12"